package co.edu.fcv.citas.identity;

import co.edu.fcv.citas.CitasApiApplication;
import co.edu.fcv.citas.support.TestDatabase;
import org.junit.jupiter.api.*; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc; import org.springframework.boot.test.context.SpringBootTest; import org.springframework.http.MediaType; import org.springframework.test.web.servlet.MockMvc;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*; import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

@SpringBootTest(classes=CitasApiApplication.class) @AutoConfigureMockMvc class IdentityExtensionIntegrationTest {
 @Autowired MockMvc mvc; @Autowired TestDatabase database;
 private final String body="{\"firstName\":\"Fase\",\"lastName\":\"Cuatro\",\"documentType\":\"CC\",\"documentNumber\":\"778899\",\"email\":\"fase4@example.com\",\"phone\":\"3001112233\",\"password\":\"password-segura\"}";
 @BeforeEach void clean(){database.reset();}
 @Test void userCanReadAndChangeOnlyOwnPhone() throws Exception {register();String token=login("password-segura");mvc.perform(get("/api/v1/users/me").header("Authorization","Bearer "+token)).andExpect(status().isOk()).andExpect(jsonPath("$.email").value("fase4@example.com"));mvc.perform(patch("/api/v1/users/me").header("Authorization","Bearer "+token).contentType(MediaType.APPLICATION_JSON).content("{\"phone\":\"3009998877\"}")).andExpect(status().isOk()).andExpect(jsonPath("$.phone").value("3009998877"));}
 @Test void recoveryIsGenericAndTokenIsSingleUse() throws Exception {register();mvc.perform(post("/api/v1/auth/password-recovery").contentType(MediaType.APPLICATION_JSON).content("{\"email\":\"unknown@example.com\"}")).andExpect(status().isAccepted());mvc.perform(post("/api/v1/auth/password-recovery").contentType(MediaType.APPLICATION_JSON).content("{\"email\":\"fase4@example.com\"}")).andExpect(status().isAccepted());database.grantRole("fase4@example.com","ADMIN");String token=login("password-segura");String reset=mvc.perform(get("/api/v1/admin/local-mailbox/password-recovery").header("Authorization","Bearer "+token)).andExpect(status().isOk()).andExpect(jsonPath("$[0].token").isNotEmpty()).andReturn().getResponse().getContentAsString().replaceAll(".*\\\"token\\\":\\\"([^\\\"]+)\\\".*","$1");String resetBody="{\"token\":\""+reset+"\",\"password\":\"nueva-clave-segura\",\"confirmation\":\"nueva-clave-segura\"}";mvc.perform(post("/api/v1/auth/password-reset").contentType(MediaType.APPLICATION_JSON).content(resetBody)).andExpect(status().isNoContent());mvc.perform(post("/api/v1/auth/password-reset").contentType(MediaType.APPLICATION_JSON).content(resetBody)).andExpect(status().isUnauthorized());mvc.perform(post("/api/v1/auth/login").contentType(MediaType.APPLICATION_JSON).content("{\"email\":\"fase4@example.com\",\"password\":\"nueva-clave-segura\"}")).andExpect(status().isOk());}
 @Test void epsAndPlanAreAdminOnlyAndRegistrationAcceptsActivePlan() throws Exception {register();String userToken=login("password-segura");mvc.perform(post("/api/v1/admin/eps").header("Authorization","Bearer "+userToken).contentType(MediaType.APPLICATION_JSON).content("{\"name\":\"EPS Prueba\"}")).andExpect(status().isForbidden());database.grantRole("fase4@example.com","ADMIN");String admin=login("password-segura");var eps=mvc.perform(post("/api/v1/admin/eps").header("Authorization","Bearer "+admin).contentType(MediaType.APPLICATION_JSON).content("{\"name\":\"EPS Prueba\"}")).andExpect(status().isOk()).andReturn().getResponse().getContentAsString();String epsId=eps.replaceAll(".*\\\"id\\\":(\\d+).*","$1");var plan=mvc.perform(post("/api/v1/admin/eps-plans").header("Authorization","Bearer "+admin).contentType(MediaType.APPLICATION_JSON).content("{\"epsId\":"+epsId+",\"name\":\"Plan Base\"}")).andExpect(status().isOk()).andReturn().getResponse().getContentAsString();String planId=plan.replaceAll(".*\\\"id\\\":(\\d+).*","$1");mvc.perform(post("/api/v1/auth/register").contentType(MediaType.APPLICATION_JSON).content("{\"firstName\":\"Con\",\"lastName\":\"Plan\",\"documentType\":\"CC\",\"documentNumber\":\"112233\",\"email\":\"plan@example.com\",\"phone\":\"3003334455\",\"password\":\"password-segura\",\"insurancePlanId\":"+planId+"}")).andExpect(status().isCreated());}
 private void register() throws Exception {mvc.perform(post("/api/v1/auth/register").contentType(MediaType.APPLICATION_JSON).content(body)).andExpect(status().isCreated());}
 private String login(String password) throws Exception {return mvc.perform(post("/api/v1/auth/login").contentType(MediaType.APPLICATION_JSON).content("{\"email\":\"fase4@example.com\",\"password\":\""+password+"\"}")).andExpect(status().isOk()).andReturn().getResponse().getContentAsString().replaceAll(".*\\\"accessToken\\\":\\\"([^\\\"]+)\\\".*","$1");}
}
