package co.edu.fcv.citas.scheduling;
import co.edu.fcv.citas.shared.web.ApiException;
import java.time.*; import java.util.*; import org.springframework.http.HttpStatus; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.security.core.*; import org.springframework.security.core.context.SecurityContextHolder; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.bind.annotation.*;

/** Booking adapter for the official 3FN appointment/slot model. */
@RestController @RequestMapping("/api/v1")
public class SchedulingController {
 private final JdbcTemplate db; private final AppointmentStatusHistory history; public SchedulingController(JdbcTemplate db,AppointmentStatusHistory history){this.db=db;this.history=history;}
 private long actor(){Authentication a=SecurityContextHolder.getContext().getAuthentication();if(a==null||!a.isAuthenticated())throw new ApiException(HttpStatus.UNAUTHORIZED,"Autenticación requerida");return Long.parseLong(a.getName());}
 @GetMapping("/booking/locations") public List<Map<String,Object>> locations(){return db.query("select id,code,name from locations where active=true order by name",(rs,n)->Map.<String,Object>of("id",rs.getLong(1),"code",rs.getString(2),"name",rs.getString(3)));}
 @GetMapping("/catalogs/specialties") public List<Map<String,Object>> specialties(){return db.query("select id,code,name,appointment_duration_minutes,requires_admin_approval from specialties where active=true order by name",(rs,n)->Map.<String,Object>of("id",rs.getLong(1),"code",rs.getString(2),"name",rs.getString(3),"durationMinutes",rs.getInt(4),"requiresAdminApproval",rs.getBoolean(5)));}
 @GetMapping("/catalogs/professionals") public List<Map<String,Object>> professionals(@RequestParam long specialtyId,@RequestParam long locationId){return db.query("select distinct p.id,concat(u.first_name,' ',u.last_name),p.professional_code from professionals p join users u on u.id=p.user_id join professional_specialties ps on ps.professional_id=p.id join specialties s on s.id=ps.specialty_id join professional_locations pl on pl.professional_id=p.id where p.active=true and ps.active=true and s.active=true and pl.active=true and ps.specialty_id=? and pl.location_id=? order by 2",(rs,n)->Map.<String,Object>of("id",rs.getLong(1),"name",rs.getString(2),"professionalCode",rs.getString(3)),specialtyId,locationId);}
 @GetMapping("/availability") public List<Map<String,Object>> availability(@RequestParam long professionalId,@RequestParam long locationId,@RequestParam long specialtyId,@RequestParam LocalDate date){
  int duration=duration(specialtyId); int needed=duration/30;
  if(!offers(professionalId,specialtyId,locationId))return List.of(); // RN-08: solo especialidad activa asociada al profesional
  List<LocalDateTime> starts=db.query("select ps.start_at from professional_slots ps join availability_blocks ab on ab.id=ps.availability_block_id where ab.professional_id=? and ab.location_id=? and ab.active=true and ps.appointment_id is null and ps.start_at>=? and ps.start_at<? order by ps.start_at",(rs,n)->rs.getTimestamp(1).toLocalDateTime(),professionalId,locationId,java.sql.Timestamp.valueOf(date.atStartOfDay()),java.sql.Timestamp.valueOf(date.plusDays(1).atStartOfDay()));
  List<Map<String,Object>> out=new ArrayList<>(); for(LocalDateTime start:starts){int count=db.queryForObject("select count(*) from professional_slots ps join availability_blocks ab on ab.id=ps.availability_block_id where ab.professional_id=? and ab.location_id=? and ps.appointment_id is null and ps.start_at>=? and ps.end_at<=?",Integer.class,professionalId,locationId,start,start.plusMinutes(duration));if(count==needed)out.add(Map.of("startAt",start.toString(),"endAt",start.plusMinutes(duration).toString(),"durationMinutes",duration));}return out;
 }
 @PostMapping("/appointments") @Transactional public Map<String,Object> reserve(@RequestBody BookingInput input){
  long user=actor(); LocalDateTime start=parse(input.startAt()); int duration=duration(input.specialtyId()); LocalDateTime end=start.plusMinutes(duration);
  if(!offers(input.professionalId(),input.specialtyId(),input.locationId()))throw conflict("La selección no está disponible");
  List<Long> slots=db.query("select ps.id from professional_slots ps join availability_blocks ab on ab.id=ps.availability_block_id where ab.professional_id=? and ab.location_id=? and ps.start_at>=? and ps.end_at<=? and ps.appointment_id is null order by ps.start_at for update",(rs,n)->rs.getLong(1),input.professionalId(),input.locationId(),start,end);
  if(slots.size()!=duration/30)throw conflict("El horario ya no está disponible");
  boolean approval=db.queryForObject("select requires_admin_approval from specialties where id=? and active=true",Boolean.class,input.specialtyId()); long status=db.queryForObject("select id from appointment_statuses where code=?",Long.class,approval?"REQUESTED":"APPROVED"); Long affiliation=currentAffiliation(user);
  db.update("insert into appointments(patient_user_id,professional_id,location_id,specialty_id,insurance_affiliation_id,status_id,reason,scheduled_start_at,scheduled_end_at,created_by_user_id,approved_at) values(?,?,?,?,?,?,?,?,?,?,?)",user,input.professionalId(),input.locationId(),input.specialtyId(),affiliation,status,blank(input.reason()),start,end,user,approval?null:LocalDateTime.now());
  long id=db.queryForObject("select last_insert_id()",Long.class); for(long slot:slots)db.update("update professional_slots set appointment_id=? where id=?",id,slot);
  history.record(id,approval?"REQUESTED":"APPROVED",approval?user:null,approval?"USER":"SYSTEM",approval?"Solicitud especializada creada":"Aprobación automática de Medicina General");
  return Map.of("id",id,"status",approval?"REQUESTED":"APPROVED","startAt",start.toString(),"endAt",end.toString());
 }
 /** RN-07/RN-08: profesional activo, especialidad activa asociada y sede asignada. */
 private boolean offers(long professional,long specialty,long location){return db.queryForObject("select count(*) from professionals p join professional_specialties ps on ps.professional_id=p.id join specialties s on s.id=ps.specialty_id join professional_locations pl on pl.professional_id=p.id where p.id=? and p.active=true and ps.specialty_id=? and ps.active=true and s.active=true and pl.location_id=? and pl.active=true",Integer.class,professional,specialty,location)>0;}
 private Long currentAffiliation(long user){List<Long> r=db.query("select id from user_insurance_affiliations where user_id=? and is_current=true",(rs,n)->rs.getLong(1),user);return r.isEmpty()?null:r.getFirst();}
 /** RF-09: la duración sale del catálogo; una especialidad inexistente o inactiva no es reservable (RN-08). */
 private int duration(long specialty){List<Integer> r=db.queryForList("select appointment_duration_minutes from specialties where id=? and active=true",Integer.class,specialty);if(r.isEmpty())throw new ApiException(HttpStatus.NOT_FOUND,"Especialidad no existe o está inactiva");return r.getFirst();}
 private static LocalDateTime parse(String v){try{return LocalDateTime.parse(v);}catch(Exception e){throw new ApiException(HttpStatus.BAD_REQUEST,"Use fecha y hora YYYY-MM-DDTHH:mm");}} private static String blank(String s){return s==null||s.isBlank()?null:s.trim();} private static ApiException conflict(String s){return new ApiException(HttpStatus.CONFLICT,s);}
 public record BookingInput(long professionalId,long locationId,long specialtyId,String startAt,String reason){}
}
