package co.edu.fcv.citas.identity;
import co.edu.fcv.citas.auth.ApiException;
import java.nio.charset.StandardCharsets; import java.security.*; import java.time.*; import java.util.*;
import org.springframework.http.*; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.security.core.*; import org.springframework.security.core.context.SecurityContextHolder; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.bind.annotation.*;

/** Identity/profile endpoints mapped to the professor's normalized schema. */
@RestController @RequestMapping("/api/v1")
public class IdentityExtensionController {
 private final JdbcTemplate db; private final PasswordEncoder passwords;
 public IdentityExtensionController(JdbcTemplate db,PasswordEncoder passwords){this.db=db;this.passwords=passwords;}
 private long actor(){Authentication a=SecurityContextHolder.getContext().getAuthentication();if(a==null||!a.isAuthenticated())throw new ApiException(HttpStatus.UNAUTHORIZED,"Autenticación requerida");try{return Long.parseLong(a.getName());}catch(Exception e){throw new ApiException(HttpStatus.UNAUTHORIZED,"Usuario inválido");}}
 private void admin(){if(SecurityContextHolder.getContext().getAuthentication().getAuthorities().stream().noneMatch(a->a.getAuthority().equals("ROLE_ADMIN")))throw new ApiException(HttpStatus.FORBIDDEN,"Rol insuficiente");}
 @GetMapping("/users/me") public Map<String,Object> me(){long id=actor();List<Map<String,Object>> r=db.queryForList("select id,first_name,last_name,document_type,document_number,email,phone from users where id=? and active=true",id);if(r.isEmpty())throw new ApiException(HttpStatus.UNAUTHORIZED,"Usuario no existe");Map<String,Object> u=r.getFirst();return Map.of("id",String.valueOf(u.get("id")),"firstName",u.get("first_name"),"lastName",u.get("last_name"),"documentType",u.get("document_type"),"documentNumber",u.get("document_number"),"email",u.get("email"),"phone",u.get("phone"),"roles",db.query("select r.code from roles r join user_roles ur on ur.role_id=r.id where ur.user_id=?",(rs,n)->rs.getString(1),id));}
 @PatchMapping("/users/me") @Transactional public Map<String,Object> phone(@RequestBody PhonePatch p){if(p.phone()==null||p.phone().isBlank())throw new ApiException(HttpStatus.BAD_REQUEST,"Teléfono obligatorio");db.update("update users set phone=? where id=?",p.phone().trim(),actor());return me();}
 @GetMapping("/users/me/affiliation") public Map<String,Object> affiliation(){List<Map<String,Object>> r=db.query("select a.plan_id,p.name,e.id,e.name,ir.code from user_insurance_affiliations a join eps_plans p on p.id=a.plan_id join eps e on e.id=p.eps_id join insurance_regimes ir on ir.id=p.regime_id where a.user_id=? and a.is_current=true",(rs,n)->Map.<String,Object>of("insurancePlanId",rs.getLong(1),"planName",rs.getString(2),"epsId",rs.getLong(3),"epsName",rs.getString(4),"regimeCode",rs.getString(5)),actor());return r.isEmpty()?Map.of():r.getFirst();}
 @PutMapping("/users/me/affiliation") @Transactional public void affiliation(@RequestBody AffiliationInput input){long user=actor();if(db.queryForObject("select count(*) from eps_plans where id=? and active=true",Integer.class,input.insurancePlanId())==0)throw new ApiException(HttpStatus.BAD_REQUEST,"Plan inexistente o inactivo");db.update("update user_insurance_affiliations set is_current=false,valid_to=curdate() where user_id=? and is_current=true",user);db.update("insert into user_insurance_affiliations(user_id,plan_id,membership_number,is_current,valid_from) values(?,?,?,true,curdate())",user,input.insurancePlanId(),"AF-"+user+"-"+UUID.randomUUID().toString().substring(0,8));}
 @GetMapping("/catalogs/eps") public List<Map<String,Object>> eps(@RequestParam(defaultValue="true") boolean active){return db.queryForList("select id,name,active from eps where active=? order by name",active);}
 @GetMapping("/catalogs/eps-plans") public List<Map<String,Object>> plans(@RequestParam long epsId,@RequestParam(defaultValue="true") boolean active){return db.queryForList("select id,eps_id epsId,name,active from eps_plans where eps_id=? and active=? order by name",epsId,active);}
 @GetMapping("/admin/eps") public List<Map<String,Object>> adminEps(){admin();return db.queryForList("select id,name,active from eps order by name");}
 @PostMapping("/admin/eps") @Transactional public Map<String,Object> createEps(@RequestBody NameInput i){admin();String name=req(i.name());String code="EPS"+UUID.randomUUID().toString().replace("-","").substring(0,10).toUpperCase();db.update("insert into eps(code,name,active) values(?,?,true)",code,name);return db.queryForMap("select id,name,active from eps where code=?",code);}
 @PatchMapping("/admin/eps/{id}") @Transactional public void patchEps(@PathVariable long id,@RequestBody NameActivePatch p){admin();if(p.name()==null&&p.active()==null)throw new ApiException(HttpStatus.BAD_REQUEST,"Indique un cambio");if(db.update("update eps set name=coalesce(?,name),active=coalesce(?,active) where id=?",blank(p.name()),p.active(),id)==0)throw new ApiException(HttpStatus.NOT_FOUND,"EPS no existe");}
 @GetMapping("/admin/eps-plans") public List<Map<String,Object>> adminPlans(){admin();return db.queryForList("select id,eps_id epsId,name,active from eps_plans order by name");}
 @PostMapping("/admin/eps-plans") @Transactional public Map<String,Object> createPlan(@RequestBody PlanInput i){admin();if(db.queryForObject("select count(*) from eps where id=?",Integer.class,i.epsId())==0)throw new ApiException(HttpStatus.BAD_REQUEST,"EPS no existe");long regime=db.queryForObject("select id from insurance_regimes order by id limit 1",Long.class);String code="PLAN"+UUID.randomUUID().toString().replace("-","").substring(0,10).toUpperCase();db.update("insert into eps_plans(eps_id,regime_id,code,name,active) values(?,?,?,?,true)",i.epsId(),regime,code,req(i.name()));return db.queryForMap("select id,eps_id epsId,name,active from eps_plans where code=?",code);}
 @PostMapping("/auth/password-recovery") public ResponseEntity<Void> recover(@RequestBody RecoveryRequest r){return ResponseEntity.accepted().build();}
 private static String req(String v){if(v==null||v.isBlank())throw new ApiException(HttpStatus.BAD_REQUEST,"Nombre obligatorio");return v.trim();} private static String blank(String v){return v==null||v.isBlank()?null:v.trim();}
 public record PhonePatch(String phone){} public record AffiliationInput(long insurancePlanId,String regimeCode){} public record NameInput(String name){} public record NameActivePatch(String name,Boolean active){} public record PlanInput(long epsId,String name){} public record RecoveryRequest(String email){}
}
